version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: finalproject-hotel-management-system-mysql
    environment:
      MYSQL_ROOT_PASSWORD: yazan1181463
      MYSQL_DATABASE: HotelManagementSystem
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql


  springboot-app:
    build: .
    container_name: finalproject-hotel-management-system-springboot  # Updated container name for Spring Boot app
    ports:
      - "8081:8080"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://finalproject-hotel-management-system-mysql:3306/HotelManagementSystem?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: yazan1181463
      JAVA_OPTS: "-Xmx512m -Xms256m"  # Example: Adjust JVM memory settings

volumes:
  mysql-data:
