version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: finalproject-hotel-management-system-mysql  # Updated container name for MySQL
    environment:
      MYSQL_ROOT_PASSWORD: yazan1181463  # Replace with your MySQL root password
      MYSQL_DATABASE: HotelManagementSystem  # Replace with your MySQL database name
      MYSQL_USER: root  # Replace with your MySQL username
      MYSQL_PASSWORD: yazan1181463  # Replace with your MySQL password
    ports:
      - "3307:3306"  # Map container's port 3306 to host port 3307
    volumes:
      - mysql-data:/var/lib/mysql

  springboot-app:
    build: .
    container_name: finalproject-hotel-management-system-springboot  # Updated container name for Spring Boot app
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://finalproject-hotel-management-system-mysql:3306/HotelManagementSystem?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: yazan1181463

volumes:
  mysql-data:
